/**
 * product list type
 */

const ShopType = {
    FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
    FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
    FETCH_COLLECTION_ERROR: "FETCH_COLLECTION_ERROR",
}


export default ShopType;

