/**
 * announcement type
 */

const AnnouncementType = {
    FETCH_ANNOUNCEMENT_START: 'FETCH_ANNOUNCEMENT_START',
    FETCH_ANNOUNCEMENT_SUCCESS: 'FETCH_ANNOUNCEMENT_SUCCESS',
    FETCH_ANNOUNCEMENT_ERROR: 'FETCH_ANNOUNCEMENT_ERROR'
}

export default AnnouncementType
